dependencies:
- name: nginx-ingress
  version: 1.1.3
  repository: https://kubernetes-charts.storage.googleapis.com
- name: mysql
  version: 0.12.0
  repository: https://kubernetes-charts.storage.googleapis.com
